### ISSUE TITLE
Need function to open/close folders

### ISSUE THREAD

**Issue by customlogic** [dataarts/dat.guiVR#82]
It's helpful to have certain nested folders closed by default. We should expose a function to open/close folders via JS

**Comment by xinaesthete** [comment]
I had a quick go at this since it's fresh in my mind. Will submit PR.

If you call `open()` on a folder whose parent (and/or maybe grandparent etc) is currently closed, should they be opened as well so that the folder you specify as opening gets a chance to be seen? Or should it be the responsibility of the caller?

**Comment by customlogic** [comment]
Thanks! I think it's okay if the responsibility of opening the parent is on the user.. Too many magic/automatic processes can cause new problems for people.

**Comment by xinaesthete** [comment]
I think this can be closed now that the PR was merged.
